/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaMeRouteImport } from './routes/ba-me'
import { Route as GiaoTrinhRouteImport } from './routes/giao-trinh'
import { Route as HoiDapRouteImport } from './routes/hoi-dap'
import { Route as LoTrinhRouteImport } from './routes/lo-trinh'
import { Route as BaiHocIndexRouteImport } from './routes/bai-hoc.index'
import { Route as BaiHocSlugRouteImport } from './routes/bai-hoc.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaMeRoute = BaMeRouteImport.update({
  id: '/ba-me',
  path: '/ba-me',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaoTrinhRoute = GiaoTrinhRouteImport.update({
  id: '/giao-trinh',
  path: '/giao-trinh',
  getParentRoute: () => rootRouteImport,
} as any)
const HoiDapRoute = HoiDapRouteImport.update({
  id: '/hoi-dap',
  path: '/hoi-dap',
  getParentRoute: () => rootRouteImport,
} as any)
const LoTrinhRoute = LoTrinhRouteImport.update({
  id: '/lo-trinh',
  path: '/lo-trinh',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiHocIndexRoute = BaiHocIndexRouteImport.update({
  id: '/bai-hoc/',
  path: '/bai-hoc/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiHocSlugRoute = BaiHocSlugRouteImport.update({
  id: '/bai-hoc/$slug',
  path: '/bai-hoc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ba-me': typeof BaMeRoute
  '/giao-trinh': typeof GiaoTrinhRoute
  '/hoi-dap': typeof HoiDapRoute
  '/lo-trinh': typeof LoTrinhRoute
  '/bai-hoc/$slug': typeof BaiHocSlugRoute
  '/bai-hoc/': typeof BaiHocIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ba-me': typeof BaMeRoute
  '/giao-trinh': typeof GiaoTrinhRoute
  '/hoi-dap': typeof HoiDapRoute
  '/lo-trinh': typeof LoTrinhRoute
  '/bai-hoc/$slug': typeof BaiHocSlugRoute
  '/bai-hoc': typeof BaiHocIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ba-me': typeof BaMeRoute
  '/giao-trinh': typeof GiaoTrinhRoute
  '/hoi-dap': typeof HoiDapRoute
  '/lo-trinh': typeof LoTrinhRoute
  '/bai-hoc/$slug': typeof BaiHocSlugRoute
  '/bai-hoc/': typeof BaiHocIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ba-me'
    | '/giao-trinh'
    | '/hoi-dap'
    | '/lo-trinh'
    | '/bai-hoc/$slug'
    | '/bai-hoc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ba-me'
    | '/giao-trinh'
    | '/hoi-dap'
    | '/lo-trinh'
    | '/bai-hoc/$slug'
    | '/bai-hoc'
  id:
    | '__root__'
    | '/'
    | '/ba-me'
    | '/giao-trinh'
    | '/hoi-dap'
    | '/lo-trinh'
    | '/bai-hoc/$slug'
    | '/bai-hoc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaMeRoute: typeof BaMeRoute
  GiaoTrinhRoute: typeof GiaoTrinhRoute
  HoiDapRoute: typeof HoiDapRoute
  LoTrinhRoute: typeof LoTrinhRoute
  BaiHocSlugRoute: typeof BaiHocSlugRoute
  BaiHocIndexRoute: typeof BaiHocIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ba-me': {
      id: '/ba-me'
      path: '/ba-me'
      fullPath: '/ba-me'
      preLoaderRoute: typeof BaMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giao-trinh': {
      id: '/giao-trinh'
      path: '/giao-trinh'
      fullPath: '/giao-trinh'
      preLoaderRoute: typeof GiaoTrinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoi-dap': {
      id: '/hoi-dap'
      path: '/hoi-dap'
      fullPath: '/hoi-dap'
      preLoaderRoute: typeof HoiDapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lo-trinh': {
      id: '/lo-trinh'
      path: '/lo-trinh'
      fullPath: '/lo-trinh'
      preLoaderRoute: typeof LoTrinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-hoc/': {
      id: '/bai-hoc/'
      path: '/bai-hoc'
      fullPath: '/bai-hoc/'
      preLoaderRoute: typeof BaiHocIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-hoc/$slug': {
      id: '/bai-hoc/$slug'
      path: '/bai-hoc/$slug'
      fullPath: '/bai-hoc/$slug'
      preLoaderRoute: typeof BaiHocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaMeRoute: BaMeRoute,
  GiaoTrinhRoute: GiaoTrinhRoute,
  HoiDapRoute: HoiDapRoute,
  LoTrinhRoute: LoTrinhRoute,
  BaiHocSlugRoute: BaiHocSlugRoute,
  BaiHocIndexRoute: BaiHocIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
